Generate CMake package configuration files
zlib-ng/zlib-ng pull request #1647
Opened 2024-01-23 05:45 UTC by mtl1979

* For COMPAT mode, ZLIB-config.cmake and ZLIB-config-version.cmake
* For non-COMPAT mode, zlib-ng-config.cmake and zlib-ng-config-version.cmake

See #1646.

2024-01-23 14:24 UTC, bebuch requested changes
With this changes the patch works for me. I tested only `ZLIB_COMPAT=ON`.

2024-01-23 14:24 UTC, bebuch commented on zlib-config.cmake.in
> +
Add targets file to import the Target `ZLIB::ZLIB`.

```cmake
include("${CMAKE_CURRENT_LIST_DIR}/ZLIB.cmake")
```

2024-01-23 14:24 UTC, bebuch commented on zlib-ng-config.cmake.in
> +
Add targets file to import the Target `zlib-ng::zlib-ng`.

```cmake
include("${CMAKE_CURRENT_LIST_DIR}/zlib-ng.cmake")
```

2024-01-23 17:18 UTC, bebuch approved these changes
lgtm

2024-01-23 17:54 UTC, nmoinvaz commented
> For COMPAT mode, ZLIB-config.cmake and ZLIB-config-version.cmake

You mean "zlib-config.cmake" and "zlib-config-version.cmake" correct? Difference in casing.

2024-01-23 18:30 UTC, mtl1979 commented
> > For COMPAT mode, ZLIB-config.cmake and ZLIB-config-version.cmake
> 
> You mean "zlib-config.cmake" and "zlib-config-version.cmake" correct? Difference in casing.

Yup... I fixed the casing in actual files to match cmake documentation but forgot to update commit message ;)

2024-01-23 18:32 UTC, flagarde commented
It seems CMake have a variable `ZLIB_LIBRARIES` in https://cmake.org/cmake/help/latest/module/FindZLIB.html, maybe it could be nice to have this one for compatibility ?

2024-01-23 18:41 UTC, mtl1979 commented
> It seems CMake have a variable `ZLIB_LIBRARIES` in https://cmake.org/cmake/help/latest/module/FindZLIB.html, maybe it could be nice to have this one for compatibility ?

FindZLIB module is used by find_package(ZLIB), which will call these files before setting `ZLIB_LIBRARIES` ,,, This is also why the last line exists in *-config.cmake.in even though there is no components defined in zlib or zlib-ng. The last line will set either `ZLIB_FOUND` or `zlib-ng_FOUND` if all the given parameters are valid and supported.

The new files allow requesting specific minimum version of zlib or zlib-ng. Not all cmake versions we want to support allow setting the version range to match minor version which would have been another choice.

2024-01-24 13:18 UTC, Dead2 commented
Is there any reason to keep the case difference in `ZLIB_FOUND` or `zlib-ng_FOUND`?
If part of the variable is in caps, then it would be much more logical that the whole thing is in caps. The mixed case kind of screams `WARNING` ;)

2024-01-24 13:31 UTC, mtl1979 commented
> Is there any reason to keep the case difference in `ZLIB_FOUND` or `zlib-ng_FOUND`? If part of the variable is in caps, then it would be much more logical that the whole thing is in caps. The mixed case kind of screams `WARNING` ;)
> 
> Edit: Similar question goes for the other variables where there is `ZLIB` and `zlib-ng`, not as bad but also looks funny where we/users can see them both.

Cmake is case-sensitive... When concatenating tokens, it's quite common to have mixed-case tokens as result. If we change everything to either lowercase or uppercase, it would break a lot of third-party projects and cmake modules.

Some cmake's functions assume tokens are lowercase, but others assume camelcase. Some functions accept both variants and treat them as equal, but that's kinda an exception.

2024-01-24 13:42 UTC, Dead2 commented
> Cmake is case-sensitive... When concatenating tokens, it's quite common to have mixed-case tokens as result. If we change everything to either lowercase or uppercase, it would break a lot of third-party projects and cmake modules.

Sure, but would that break for for example `zlib-ng_FOUND`? I am under the impression that that is a new variable we have not exported before? (Or did we in the last release perhaps?)

Not a big issue, just want to make sure we make it as logical as possible before we release it and have to worry about backwards compatibility.

2024-01-24 13:52 UTC, mtl1979 commented
> Sure, but would that break for for example `zlib-ng_FOUND`? I am under the impression that that is a new variable we have not exported before? (Or did we in the last release perhaps?)
> 
> Not a big issue, just want to make sure we make it as logical as possible before we release it and have to worry about backwards compatibility.

Underscore here is kind of namespace separator... First token is lowercase and the second token is uppercase... It has been established convention that tokens internal to cmake are uppercase and everything else is lowercase. I haven't checked when the transition from uppercase to lowercase or lowercase to camelcase did happen, but cmake documentation already prefers camelcase over lowercase or uppercase for third-party tokens including filenames.

I've seen very old project files that expected `zlib_FOUND` instead of `ZLIB_FOUND`, which meant that the package name for zlib has changed once before, thus breaking some projects depending on which cmake version was used.

2024-01-27 23:16 UTC, Dead2 approved these changes

2024-01-28 00:04 UTC, nmoinvaz commented
> Is there any reason to keep the case difference in ZLIB_FOUND or zlib-ng_FOUND?
I think I have only seen `find_package` export all uppercase variable names.

2024-01-28 00:07 UTC, nmoinvaz commented
Actually, it looks like it might prefer lowercase at least in the filename:
![image](https://github.com/zlib-ng/zlib-ng/assets/1364432/f8bb28f5-ea76-40b4-b1b8-4624e90e0289)
https://cmake.org/cmake/help/latest/command/find_package.html

2024-01-28 00:14 UTC, mtl1979 commented
> > Is there any reason to keep the case difference in ZLIB_FOUND or zlib-ng_FOUND?
> 
> I think I have only seen `find_package` export all uppercase variable names.

There is also the case of `-` being reserved character, so using `ZLIB-NG` would be equal to defining `ZLIB` with component name `NG`... I tried looking up the specifics of how setting `<PackageName>_FOUND` handles case differences, but the documentation is lacking in that respect... It might even use the passed in `PackageName` verbatim without any normalisation.

2024-01-30 19:51 UTC, merged