Clean up zng_tr_tally code
zlib-ng/zlib-ng pull request #547
Opened 2020-03-05 02:37 UTC by nmoinvaz

Now that we have `deflate_p.h` we don't need to have a #define for inlining and separate function for debugging. We can just have a single static inline function in `deflate_p.h`. I split the whole function into two, one for tallying literal and distance, similar to how the #defines were previously split up.

2020-03-05 03:46 UTC, mtl1979 requested changes

2020-03-05 03:46 UTC, mtl1979 commented on deflate_p.h
> +    unsigned char cc = (c);
Because this is private internal function, we don't need the second parameter to be "unsigned c", we can use "unsigned char c" directly...

2020-03-08 11:10 UTC, nmoinvaz commented on deflate_p.h
> +    unsigned char cc = (c);
Fixed. Thank you.

2020-03-13 12:04 UTC, Dead2 commented
Looks a lot like what I was trying to do a month or two back, but approached from the other end.
I like it.
Performance is within measurement accuracy, except for deflate_medium that seems to have gotten very slightly faster, for obvious reasons.

2020-03-13 12:04 UTC, merged